export const BATCH_MODE_ACTION_TYPES = {
  FLUSH_STATE: 'BATCH_FLUSH_STATE',
  SET_PROCESSING_IMAGES: 'BATCH_SET_PROCESSING_FILES',
  SET_MATCHING_IMAGES: 'BATCH_SET_MATCHING_FILES',
  CLEAR_MATCHING_IMAGES: 'BATCH_CLEAR_MATCHING_IMAGES',
  SET_CONFIG_FILE: 'BATCH_SET_CONFIG_FILE',
  CLEAR_CONFIG_FILE: 'BATCH_CLEAR_CONFIG_FILE',
  SET_RESULTS: 'BATCH_SET_RESULTS',
  CLEAR_RESULTS: 'BATCH_CLEAR_RESULTS',
};

// STEP MODE ACTION TYPES
export const STEP_FLUSH_STATE = 'STEP_FLUSH_STATE';
export const STEP_MODE_INIT = 'STEP_MODE_INIT';
export const STEP_IMAGE_SELECTED = 'IMAGE_SELECTED';
export const STEP_SET_CURRENT_IMAGE = 'STEP_SET_CURRENT_IMAGE';
export const STEP_REVERT_LAST_STEP = 'STEP_REVERT_LAST_STEP';
export const STEP_ADD_HISTORY_ENTRY = 'STEP_ADD_HISTORY_ENTRY';
