// BATCH MODE ACTION TYPES
export const BATCH_FLUSH_STATE = 'BATCH_FLUSH_STATE';
export const BATCH_MODE_INIT = 'BATCH_MODE_INIT';

// STEP MODE ACTION TYPES
export const STEP_FLUSH_STATE = 'STEP_FLUSH_STATE';
export const STEP_MODE_INIT = 'STEP_MODE_INIT';
export const STEP_IMAGE_SELECTED = 'IMAGE_SELECTED';
export const STEP_SET_CURRENT_IMAGE = 'STEP_SET_CURRENT_IMAGE';
export const STEP_REVERT_LAST_STEP = 'STEP_REVERT_LAST_STEP';
export const STEP_ADD_HISTORY_ENTRY = 'STEP_ADD_HISTORY_ENTRY';
