export const BATCH_MODE_ACTION_TYPES = {
  FLUSH_STATE: 'BATCH_FLUSH_STATE',
  SET_PROCESSING_IMAGES: 'BATCH_SET_PROCESSING_FILES',
  SET_MATCHING_IMAGES: 'BATCH_SET_MATCHING_FILES',
  CLEAR_MATCHING_IMAGES: 'BATCH_CLEAR_MATCHING_IMAGES',
  SET_CONFIG_FILE: 'BATCH_SET_CONFIG_FILE',
  CLEAR_CONFIG_FILE: 'BATCH_CLEAR_CONFIG_FILE',
  SET_RESULTS: 'BATCH_SET_RESULTS',
  CLEAR_RESULTS: 'BATCH_CLEAR_RESULTS',
};

export const STEP_MODE_ACTION_TYPES = {
  FLUSH_STATE: 'STEP_FLUSH_STATE',
  ADD_HISTORY_IMAGE_ENTRY: 'STEP_ADD_HISTORY_IMAGE',
  SET_STEP_DATA: 'STEP_SET_STEP_DATA',
  CLEAR_STEP_DATA: 'STEP_CLEAR_STEP_DATA',
};
