import {
  IMAGE_SELECTION,
  STEP_PREPROCESSING,
  STEP_SEGMENTATION,
  STEP_NORMALIZATION,
  STEP_ENCODING,
  STEP_MATCHING,
} from '../stateMachine/stateNames';

export const STEP_MODE_STEP_IDS = {
  UPLOAD: IMAGE_SELECTION,
  PREPROCESSING: STEP_PREPROCESSING,
  SEGMENTATION: STEP_SEGMENTATION,
  NORMALIZATION: STEP_NORMALIZATION,
  ENCODING: STEP_ENCODING,
  MATCHING: STEP_MATCHING,
}

export const BATCH_MODE_STEP_IDS = {

};
