export const MODE_STATES = {
  HOME: 'HOME',
  STEP_MODE: 'STEP_MODE',
  BATCH_MODE: 'BATCH_MODE',
  HISTORY_MODE: 'HISTORY_MODE',
};

export const BATCH_STEPS = {
  PROCESSED_IMAGE_SELECTION: 'PROCESSED_IMAGE_SELECTION',
  MATCH_IMAGE_SELECTION: 'MATCH_IMAGE_SELECTION',
  CONFIGURATION_SELECTION: 'CONFIGURATION_SELECTION',
  PROCESSING: 'PROCESSING',
  RESULTS_PREVIEW: 'RESULTS_PREVIEW',
  RESULT_PREVIEW: 'RESULT_PREVIEW',
};

export const STEP_STEPS = {
  IMAGE_SELECTION: 'IMAGE_SELECTION',
  PREPROCESSING: 'PREPROCESSING',
  SEGMENTATION: 'SEGMENTATION',
  NORMALIZATION: 'NORMALIZATION',
  ENCODING: 'ENCODING',
  MATCHING_IMAGE_SELECTION: 'MATCHING_IMAGE_SELECTION',
  MATCHING: 'MATCHING',
  RESULTS_PREVIEW: 'RESULTS_PREVIEW',
  RESULT_PREVIEW: 'RESULT_PREVIEW',
};
