// Modes
export const HOME = 'HOME';
export const STEP_MODE = 'STEP_MODE';
export const BATCH_MODE = 'BATCH_MODE';
export const HISTORY_MODE = 'HISTORY_MODE';

// Common state names
export const MODE_INACTIVE = 'MODE_INACTIVE';
export const IMAGE_SELECTION = 'IMAGE_SELECTION';
export const MATCHING_SELECTION = 'MATCHING_SELECTION';

// Step mode states
export const STEP_PREPROCESSING = 'STEP_PREPROCESSING';
export const STEP_SEGMENTATION = 'STEP_SEGMENTATION';
export const STEP_NORMALIZATION = 'STEP_NORMALIZATION';
export const STEP_ENCODING = 'STEP_ENCODING';
export const STEP_MATCHING = 'STEP_MATCHING';
export const STEP_RESULTS = 'STEP_RESULTS';

export const STEP_PREPROCESSING_LOADING = 'STEP_PREPROCESSING_LOADING';
export const STEP_SEGMENTATION_LOADING = 'STEP_SEGMENTATION_LOADING';
export const STEP_NORMALIZATION_LOADING = 'STEP_NORMALIZATION_LOADING';
export const STEP_ENCODING_LOADING = 'STEP_ENCODING_LOADING';
export const STEP_MATCHING_LOADING = 'STEP_MATCHING_LOADING';
export const STEP_RESULTS_LOADING = 'STEP_RESULTS_LOADING';

// Batch mode states
export const BATCH_SELECT_CONFIGURATION = 'BATCH_SELECT_CONFIGURATION';
export const BATCH_PROCESSING = 'BATCH_PROCESSING';
export const BATCH_RESULTS = 'BATCH_RESULTS';
export const BATCH_RESULT_PREVIEW = 'BATCH_RESULT_PREVIEW';
