import { STEP_STEPS } from './stateNames';
import { WIZARD_TRANSITIONS } from './transitions';

export const stepModeStates = {
  initial: [STEP_STEPS.IMAGE_SELECTION],
  states: {
    [STEP_STEPS.IMAGE_SELECTION]: {
      on: {
        [WIZARD_TRANSITIONS.NEXT]: STEP_STEPS.PREPROCESSING,
      },
    },
    [STEP_STEPS.PREPROCESSING]: {
      on: {
        [WIZARD_TRANSITIONS.PREVIOUS]: STEP_STEPS.IMAGE_SELECTION,
        [WIZARD_TRANSITIONS.NEXT]: STEP_STEPS.STEP_SEGMENTATION,
      },
    },
    [STEP_STEPS.STEP_SEGMENTATION]: {
      on: {
        [WIZARD_TRANSITIONS.PREVIOUS]: STEP_STEPS.PREPROCESSING,
        [WIZARD_TRANSITIONS.NEXT]: STEP_STEPS.STEP_NORMALIZATION,
      },
    },
    [STEP_STEPS.STEP_NORMALIZATION]: {
      on: {
        [WIZARD_TRANSITIONS.PREVIOUS]: STEP_STEPS.STEP_SEGMENTATION,
        [WIZARD_TRANSITIONS.NEXT]: STEP_STEPS.STEP_ENCODING,
      },
    },
    [STEP_STEPS.STEP_ENCODING]: {
      on: {
        [WIZARD_TRANSITIONS.PREVIOUS]: STEP_STEPS.STEP_NORMALIZATION,
        [WIZARD_TRANSITIONS.NEXT]: STEP_STEPS.MATCHING_SELECTION,
      },
    },
    [STEP_STEPS.MATCHING_SELECTION]: {
      on: {
        [WIZARD_TRANSITIONS.PREVIOUS]: STEP_STEPS.STEP_ENCODING,
        [WIZARD_TRANSITIONS.NEXT]: STEP_STEPS.STEP_MATCHING,
      },
    },
    [STEP_STEPS.STEP_MATCHING]: {
      on: {
        [WIZARD_TRANSITIONS.PREVIOUS]: STEP_STEPS.MATCHING_SELECTION,
        [WIZARD_TRANSITIONS.NEXT]: STEP_STEPS.PROCESSING,
      },
    },
    [STEP_STEPS.PROCESSING]: {
      on: {
        [WIZARD_TRANSITIONS.PROCESSING_FAILED]: STEP_STEPS.STEP_MATCHING,
        [WIZARD_TRANSITIONS.PROCESSING_FINISHED]: STEP_STEPS.RESULTS_PREVIEW,
      },
    },
    [STEP_STEPS.RESULTS_PREVIEW]: {
      on: {
        [WIZARD_TRANSITIONS.PREVIOUS]: STEP_STEPS.RESULTS_PREVIEW,
      },
    },
  },
};
