export const MODE_TRANSITIONS = {
  RETURN_HOME: 'RETURN_HOME',
  STEP_MODE_SELECTED: 'STEP_MODE_SELECTED',
  BATCH_MODE_SELECTED: 'BATCH_MODE_SELECTED',
  HISTORY_MODE_SELECTED: 'HISTORY_MODE_SELECTED',
};

export const WIZARD_TRANSITIONS = {
  NEXT: 'NEXT',
  PREVIOUS: 'PREVIOUS',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  PROCESSING_FINISHED: 'PROCESSING_FINISHED',
};
