export const RETURN_HOME = 'RETURN_HOME';
export const STEP_MODE_SELECTED = 'STEP_MODE_SELECTED';
export const BATCH_MODE_SELECTED = 'BATCH_MODE_SELECTED';
export const HISTORY_MODE_SELECTED = 'HISTORY_MODE_SELECTED';

export const NEXT_STEP = 'NEXT_STEP';
export const PREVIOUS_STEP = 'PREVIOUS_STEP';
